Algoritmo "Atividade4"
Var
   lado1, lado2, lado3: Real
   perimetro: Real
Inicio
   Escreva("Digite o comprimento do primeiro lado do triângulo: ")
   Leia(lado1)
   Escreva("Digite o comprimento do segundo lado do triângulo: ")
   Leia(lado2)
   Escreva("Digite o comprimento do terceiro lado do triângulo: ")
   Leia(lado3)
   
   perimetro := lado1 + lado2 + lado3
   
   Escreva("O perímetro do triângulo é: ", perimetro)
FimAlgoritmo