algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

i, soma: inteiro

inicio

soma <- 0
para i de 1 ate 100 faca
escreval(i)
soma <- soma + i
fimpara

escreval("A soma de todos os números de 1 a 100 é: ",soma)
fimalgoritmo