algoritmo "Par ou não"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Programa que verifica se um número é par ou ímpar.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/04/2025

var
   numero: inteiro

inicio
   escreval("Digite um número: ")
   leia(numero)

   se (numero % 2 = 0) entao
      escreval("Seu número é par.")
   senao
      escreval("Seu número não é par.")
   fimse
fimalgoritmo
