algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

numero: real

inicio

escreval("Digite um número qualquer: ")
leia(numero)
se numero >= 0 entao
escreval("Seu número é positivo")
senao 
escreval("Seu número é negativo")



fimse
fimalgoritmo